### ISSUE TITLE
Tk::Error: Undefined subroutine

### ISSUE THREAD

**Issue by dromer** [tux99/xseries_editor#1]
Hi tux99,

Ran in to your software this week and since I'm getting an 05r/w I thought about giving it a try.
However whenever I click in the menu I encounter these 'Undefined subroutine' errors.
ie. with 'File>New' (ctrl+n) or 'Edit>Combination Editor'

```
Tk::Error: Undefined subroutine &main::newVoice called at ./xseries_editor.pl line 586.
 Tk callback for .frame.menubutton.menu
 Tk::__ANON__ at /usr/lib/i386-linux-gnu/perl5/5.22/Tk.pm line 251
 Tk::Menu::Invoke at /usr/lib/i386-linux-gnu/perl5/5.22/Tk/Menu.pm line 532
 <ButtonRelease>
 (command bound to event)
Tk::Error: Undefined subroutine &main::CombEditWin called at ./xseries_editor.pl line 604.
 Tk callback for .frame.menubutton1.menu
 Tk::__ANON__ at /usr/lib/i386-linux-gnu/perl5/5.22/Tk.pm line 251
 Tk::Menu::Invoke at /usr/lib/i386-linux-gnu/perl5/5.22/Tk/Menu.pm line 532
 <ButtonRelease>
 (command bound to event)
```

regards,

**Comment by tux99** [comment]
Hi Dromer,

unfortunately the X Series Editor is not complete yet, so some features aren't working yet (File->New is one of them, the Combination Editor is another).
Basically wherever you get the 'Undefined subroutine' error, it means that that particular feature isn't implemented yet.

That said in its current state the Editor should already be usable to edit Programs in real-time on a suitable Korg synth connected via MIDI.

I'm still planning to eventually complete the Editor (it's not abandoned, just paused until I have the time for it again! ;-) ) but can't say when that will happen. 

In case you have programming skills and want to contribute code yourself, you are very welcome to do so.

**Comment by dromer** [comment]
Cool. Didn't dive into the code to figure out if there where any methods available for those buttons.
However I would be inclined to make a panel for Ctrlr instead (http://ctrlr.org/). This has the added advantage that 1) you can use it as a vst and easily do midi-mapping from a DAW 2) easily portable cross-platform 3) I have a bunch more panels I would like to make/improve

Thnx for the work and when I get a suitable module I'll try it for sure :)
